<?php


namespace PhpUnitWorkshopTest\mocks;


use Emag\Core\JiraApiBundle\Tests\Unit\TestCase;

abstract class MyTestCaseHelper extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

}