<?php


namespace PhpUnitWorkshopTest\mocks;



use PHPUnit\Framework\TestCase;

abstract class MyTestCaseHelper extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

}