<?php
/**
 * Created by IntelliJ IDEA.
 * User: VictorRentea
 * Date: 01-Aug-18
 * Time: 12:58 PM
 */

namespace PhpUnitWorkshopTest\mocks;


use PHPUnit\Framework\TestCase;

class TelemetryDiagnosticControlsTest extends MyTestCaseHelper
{

    /**
     * @var \PHPUnit_Framework_MockObject_MockObject|TelemetryClient
     */
    private $client;
    /**
     * @var TelemetryDiagnosticControls
     */
    private TelemetryDiagnosticControls $controls;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

//        $this->client = $this->createMock("PhpUnitWorkshopTest\mocks\TelemetryClient");
        $this->client = $this->createMock(TelemetryClient::class);
        $this->controls = new TelemetryDiagnosticControls($this->client);
    }

    /** @test */
    public function suucessFlow()
    {
        $this->client->method("getOnlineStatus")->willReturn(true);
        $this->client->expects($this->once())->method("disconnect");
        $this->client->expects($this->once())->method("send")->with("AT#UD"); // external protocol/format
         $this->client->method("receive")->willReturn("mushrooms");

        $this->controls->checkTransmission();
        self::assertEquals("mushrooms", $this->controls->getDiagnosticInfo());
    }

    /** @test */
    public function configuresClient()
    {
        $this->client->method("getOnlineStatus")->willReturn(true);
        $this->client->expects($this->once())
            ->method("configure")
        ; // external protocol/format

        $this->controls->checkTransmission();

    }

    /** @test */
    public function createsCorrectConfig() {
        $config = $this->controls->createConfig(7);
        self::assertEquals(TelemetryClientConfiguration::ACK_NORMAL, $config);
    }


    /** @test
     * @expectedException \Exception
     */
    public function throwsWhenNotOnline()
    {
        $this->client->method("getOnlineStatus")->willReturn(false);
        $this->controls->checkTransmission();
    }
}