<?php
/**
 * Created by IntelliJ IDEA.
 * User: VictorRentea
 * Date: 01-Aug-18
 * Time: 12:58 PM
 */

namespace PhpUnitWorkshopTest\mocks;


use PHPUnit\Framework\TestCase;


function captureArg(&$arg, TelemetryDiagnosticControlsTest $instance) {
    return $instance->callback( function($argToMock ) use ( &$arg ) {
        $arg = $argToMock;
        return true;
    } );
}
class TelemetryDiagnosticControlsTest extends TestCase
{

    private $clientMock;
    private $controls;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->clientMock = $this->createMock(TelemetryClient::class);
        $this->controls = new TelemetryDiagnosticControls($this->clientMock);
    }

    /** @test */
    public function throwsWhenNotOnline() {
        $this->expectExceptionMessage("connect");
        $this->clientMock->method("getOnlineStatus")->willReturn(false); // method stubbing

        $this->controls->checkTransmission();
    }

    /** @test */
    public function disconnects() {
        $this->clientMock->method("getOnlineStatus")->willReturn(true);
        $this->clientMock->expects($this->once())->method("disconnect");
        // $this->orderDbmMock->expects($this->once())->method("save");

        $this->controls->checkTransmission();
    }
    /** @test */
    public function sendsDiagnostic() {
        $this->clientMock->method("getOnlineStatus")->willReturn(true);
        $this->clientMock->expects($this->once())->method("send")->with("AT#UD");

        $this->controls->checkTransmission();
        self::assertTrue(true);
    }

    /** @test */
    public function receives() {
        $this->clientMock->method("getOnlineStatus")->willReturn(true); // TODO DRY!
        $this->clientMock->/*expects($this->once())->*/method("receive")->willReturn("mamaie");

        $config = new TelemetryClientConfiguration();
        $this->controls->checkTransmission($config);
        self::assertEquals("mamaie", $this->controls->getDiagnosticInfo());
    }


    /** @test */
    public function configuresClient() {
        $this->clientMock->method("getOnlineStatus")->willReturn(true); // TODO DRY!

        $config = null;
        $this->clientMock->method("configure")->with(captureArg($config, $this));

        $this->controls->checkTransmission();
        self::assertEquals(TelemetryClientConfiguration::ACK_NORMAL, $config->getAckMode());
    }


    /** @test */
    public function createConfig() {
        $config = $this->controls->createConfig();
        self::assertEquals(TelemetryClientConfiguration::ACK_NORMAL, $config->getAckMode());
        self::assertLessThan(60*1000, time() - $config->getSessionStart());
        self::assertNotNull( $config->getSessionStart());
        self::assertNotNull( time());
    }




}

// https://stackoverflow.com/questions/7822036/phpunit-get-arguments-to-a-mock-method-call