<?php


namespace PhpUnitWorkshopTest;


use PHPUnit\Framework\TestCase;


class TennisScoreDataProviderTest extends TestCase
{
    private $tennisScore;


    public function data(): array
    {
        return [
            "one" => [0, 0, "Love - Love"],
            "two" => [0, 1, "Love - Fifteen"],
            "three" => [1, 1, "Fifteen - Fifteen"]
        ];
    }

    /**
     * @dataProvider data
     */
    public function testScore(int $player1Points, int $player2Points, string $expectedScoreString): void
    {
        $this->setScore($player1Points, $player2Points);
        $actual = $this->tennisScore->getScore();
        $this->assertSame($expectedScoreString, $actual);
    }

    private function setScore($player1Points, $player2Points): string
    {
        $this->setPlayerPoints($player1Points, TennisScore::PLAYER_ONE);
        $this->setPlayerPoints($player2Points, TennisScore::PLAYER_TWO);
        return $this->tennisScore->getScore();
    }

    private function setPlayerPoints($points, $player): void
    {
        for ($i = 0; $i < $points; $i++) {
            $this->tennisScore->winPoint($player);
        }
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->tennisScore = new TennisScore();
    }

}