<?php


namespace PhpUnitWorkshopTest;


use PHPUnit\Framework\TestCase;


class TennisScoreTest extends TestCase
{
    private $tennisScore;

    /** @test */
    public function loveLove()
    {
        $actual = $this->tennisScore->getScore();

        $this->assertEquals("Love - Love", $actual);
    }

    /** @test */
    public function fifteenLove()
    {
        $this->tennisScore->winPoint(TennisScore::PLAYER_ONE);

        $actual = $this->tennisScore->getScore();

        $this->assertEquals("Fifteen - Love", $actual);
    }

    /** @test */
    public function loveFifteen()
    {
        $this->tennisScore->winPoint(TennisScore::PLAYER_TWO);
        $actual = $this->tennisScore->getScore();

        $this->assertEquals("Love - Fifteen", $actual);
    }

    /** @test */
    public function loveThirty()
    {
        $this->tennisScore->winPoint(TennisScore::PLAYER_TWO);
        $this->tennisScore->winPoint(TennisScore::PLAYER_TWO);

        $actual = $this->tennisScore->getScore();

        $this->assertEquals("Love - Thirty", $actual);
    }

    /** @test */
    public function loveForty()
    {
        $this->tennisScore->winPoint(TennisScore::PLAYER_TWO);
        $this->tennisScore->winPoint(TennisScore::PLAYER_TWO);
        $this->tennisScore->winPoint(TennisScore::PLAYER_TWO);
        $actual = $this->tennisScore->getScore();

        $this->assertEquals("Love - Forty", $actual);
    }

    /** @test */
    public function thirtyLove()
    {
        $actual = $this->setScore(2, 0);
        // $actual = $this->tennisScore->getScore();

        $this->assertEquals("Thirty - Love", $actual);
    }

    public function testDeuce5()
    {
        // arrange
        $this->setScore(5, 5);

        // act
        $actual = $this->tennisScore->getScore();

        // assert
        $this->assertEquals("Deuce", $actual);
    }
    private function setScore($player1Points, $player2Points): string
    {
        $this->setPlayerPoints($player1Points, TennisScore::PLAYER_ONE);
        $this->setPlayerPoints($player2Points, TennisScore::PLAYER_TWO);
        return $this->tennisScore->getScore();
    }

    private function setPlayerPoints($points, $player): void
    {
        for ($i = 0; $i < $points; $i++) {
            $this->tennisScore->winPoint($player);
        }
    }
    /** @test */
    public function deuce3()
    {
        $this->setScore(3, 3);

        $actual = $this->tennisScore->getScore();

        $this->assertEquals("Deuce", $actual);
    }
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->tennisScore = new TennisScore();
    }
    // /** @test */
    // public function loveForty() {
    // }

    // TODO continuati cu advantage si won

}